spring.application.name=watchlist
logging.level.org.springframework.security=DEBUG
logging.level.com.example.watchlist=DEBUG
spring.datasource.url=jdbc:postgresql://localhost:5433/watchlist
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.jpa.hibernate.ddl-auto=update